# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

name: Feature request
description: Suggest a new feature for this project
title: "[FEATURE] *descriptive_name*"
labels:
  - feature
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature request
      description: >
        A clear and concise description of what the feature would add and why you think it needs to be included.
    validations:
      required: true

  - type: checkboxes
    id: community-meeting
    attributes:
      label: Community Meeting
      options:
        - label: >
            I wish to discuss this feature in the bi-monthly PGM community meeting.
            Please join the [PGM community meeting](https://zoom-lfx.platform.linuxfoundation.org/meeting/91445523235?password=e565df23-7c6d-4d67-94e6-f5774cfd4745).
