# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

name: Improvement
description: Create a proposal for improving the internal implementation
title: "[IMPROVEMENT] *descriptive_name*"
labels:
  - improvement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to register this improvement! 
        Feel free to skip or leave brief answers in any other field. 
        Any detail you can share helps, but don't let the form stop you from opening the issue. 
        You can also edit the issue after creating it to add or remove more details.

  - type: textarea
    id: problem
    attributes:
      label: Problem faced
      description: A clear and concise description of the current problem. Why do we need to improve it?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Improvement proposal
      description: >
        A clear and concise description of the improvement proposal.
        If needed, provide multiple alternatives to the proposal.
    validations:
      required: true

  - type: checkboxes
    id: community-meeting
    attributes:
      label: Community Meeting
      options:
        - label: >
            I wish to discuss this improvement in the bi-monthly PGM community meeting.
            Please join the [PGM community meeting](https://zoom-lfx.platform.linuxfoundation.org/meeting/91445523235?password=e565df23-7c6d-4d67-94e6-f5774cfd4745).
